orte = ["comic shop","Barcelona","Rio De Janeiro","Mallorca","Yew York"]
print("The original list:")
print(orte)
print(sorted(orte))
print(orte)
print(sorted(orte,reverse=True))
print(orte)
orte.reverse()
print(orte)
orte.reverse()
print(orte)
orte.sort()
print(orte)
orte.sort(reverse=True)
print(orte)
